on:
  push:
jobs:
  e2e:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Generate 10KB of Text
        id: generate_text
        run: |
          # Generate 10KB of text (10,000 characters)
          TEXT=$(head -c 206670 < /dev/urandom | tr -dc 'A-Za-z0-9' | head -c 100000)

          echo "text=$TEXT" >> $GITHUB_OUTPUT

      - name: Generate 1MB of Text
        id: generate_file
        run: |
          # Generate 1MB of text (1,000,000 characters)
          head -c 200000 < /dev/urandom | tr -dc 'A-Za-z0-9' | head -c 100000 > generated_text.txt
          # Set the generated text as an output
          echo "file=generated_text.txt" >> $GITHUB_OUTPUT

      - name: Generate 1MB String Summary
        uses: ./
        with:
          path: ${{ steps.generate_file.outputs.file }}
          max_size: 1048576  # 1MB limit
          summary_header: '1MB String'

      - name: Generate String Summary
        uses: ./
        with:
          string: |
            This is a long string that we want to process.
            It can be any string and the action will summarize it.
          max_size: 1048576  # 1MB limit
          summary_header: 'Short Text String'

      - name: Generate 10K String Summary
        uses: ./
        with:
          string: ${{ steps.generate_text.outputs.text }}
          max_size: 1048576  # 1MB limit
          summary_header: '10KB String'

      - name: Generate complex nested json
        uses: ./
        with:
          string: |
            {
              "text_plan_path": ".dflook-terraform-github-actions/gbvfjwlp/plan.txt",
              "json_plan_path": ".dflook-terraform-github-actions/gbvfjwlp/plan.json",
              "iam_for_lambda_role": "{\"arn\":\"arn:aws:iam::269132892972:role/sitemaps_for_lambda20240925083113621800000001\",\"assume_role_policy\":\"{\\\"Statement\\\":[{\\\"Action\\\":\\\"sts:AssumeRole\\\",\\\"Effect\\\":\\\"Allow\\\",\\\"Principal\\\":{\\\"Federated\\\":\\\"arn:aws:iam::269132892972:oidc-provider/oidc.eks.eu-central-1.amazonaws.com/id/9294D5A2599534C777B69944B65BA9E2\\\",\\\"Service\\\":\\\"lambda.amazonaws.com\\\"}}],\\\"Version\\\":\\\"2012-10-17\\\"}\",\"create_date\":\"2024-09-25T08:31:13Z\",\"description\":\"\",\"force_detach_policies\":false,\"id\":\"sitemaps_for_lambda20240925083113621800000001\",\"inline_policy\":[],\"managed_policy_arns\":[\"arn:aws:iam::269132892972:policy/disco-sitemaps20240925083117544800000003\",\"arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole\"],\"max_session_duration\":3600,\"name\":\"sitemaps_for_lambda20240925083113621800000001\",\"name_prefix\":\"sitemaps_for_lambda\",\"path\":\"/\",\"permissions_boundary\":\"\",\"tags\":{},\"tags_all\":{},\"unique_id\":\"AROAT5KMSBMWIPWD5IIMS\"}",
              "sitemaps_s3_bucket": "{\"acceleration_status\":\"\",\"acl\":null,\"arn\":\"arn:aws:s3:::disco-sitemaps-dev-disc-3274\",\"bucket\":\"disco-sitemaps-dev-disc-3274\",\"bucket_domain_name\":\"disco-sitemaps-dev-disc-3274.s3.amazonaws.com\",\"bucket_prefix\":\"\",\"bucket_regional_domain_name\":\"disco-sitemaps-dev-disc-3274.s3.eu-central-1.amazonaws.com\",\"cors_rule\":[],\"force_destroy\":true,\"grant\":[{\"id\":\"\",\"permissions\":[\"READ\"],\"type\":\"Group\",\"uri\":\"http://acs.amazonaws.com/groups/global/AllUsers\"},{\"id\":\"d3ae80731926d90a257fb093e369062d689c2a427098b0dc2c0326dc861a570b\",\"permissions\":[\"FULL_CONTROL\"],\"type\":\"CanonicalUser\",\"uri\":\"\"}],\"hosted_zone_id\":\"Z21DNDUVLTQW6Q\",\"id\":\"disco-sitemaps-dev-disc-3274\",\"lifecycle_rule\":[],\"logging\":[],\"object_lock_configuration\":[],\"object_lock_enabled\":false,\"policy\":\"\",\"region\":\"eu-central-1\",\"replication_configuration\":[],\"request_payer\":\"BucketOwner\",\"server_side_encryption_configuration\":[{\"rule\":[{\"apply_server_side_encryption_by_default\":[{\"kms_master_key_id\":\"\",\"sse_algorithm\":\"AES256\"}],\"bucket_key_enabled\":false}]}],\"tags\":{},\"tags_all\":{},\"timeouts\":null,\"versioning\":[{\"enabled\":false,\"mfa_delete\":false}],\"website\":[],\"website_domain\":null,\"website_endpoint\":null}",
              "sitemaps_s3_bucket_policy": "{\"arn\":\"arn:aws:iam::269132892972:policy/disco-sitemaps20240925083117544800000003\",\"attachment_count\":1,\"description\":\"Allows to access the sitemaps S3 bucket\",\"id\":\"arn:aws:iam::269132892972:policy/disco-sitemaps20240925083117544800000003\",\"name\":\"disco-sitemaps20240925083117544800000003\",\"name_prefix\":\"disco-sitemaps\",\"path\":\"/\",\"policy\":\"{\\\"Statement\\\":[{\\\"Action\\\":\\\"s3:*\\\",\\\"Effect\\\":\\\"Allow\\\",\\\"Resource\\\":[\\\"arn:aws:s3:::disco-sitemaps-dev-disc-3274/*\\\",\\\"arn:aws:s3:::disco-sitemaps-dev-disc-3274\\\"]}],\\\"Version\\\":\\\"2012-10-17\\\"}\",\"policy_id\":\"ANPAT5KMSBMWOTLJM6BDO\",\"tags\":{},\"tags_all\":{}}",
              "sitemaps_s3_bucket_url": "disco-sitemaps-dev-disc-3274.s3.amazonaws.com"
            }
          summary_header: 'Nested Double Qouted JSON'
          data_type: 'json'
